### PR TITLE
ENTESB-17372 Adding atlasmap to dependencyManagement

### PR DESCRIPTION
**Pull request by rkorytkowski**
The goal here is to provide easier way to use Atlasmap with Fuse BOM. See https://issues.redhat.com/browse/ENTESB-17372

We'd like this to be included in Fuse 7.10.x. Is this the right branch?

### CODE REVIEW

**Comment by grgrzybek** [comment]
Thanks @rkorytkowski !
However before we merge it, let's resolve one issue described [here](https://issues.redhat.com/browse/ENTESB-17372?focusedCommentId=19107118&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19107118).

**Review by oscerd — APPROVED** [review]

**Comment by rkorytkowski** [comment]
@grgrzybek @oscerd just a follow up. Is there anything else to do before merging?

**Review by cunningt — APPROVED** [review]
Looks good!

**Comment by rkorytkowski** [comment]
Thanks for approvals! Shall I merge it myself or what's the process?

**Pull request merged**
