### PR TITLE
ENTESB-9455 - respect m2e configuration

### PR DESCRIPTION
**Pull request by apupier**
I wasn't able to test it for all plugins, only the spring-boot maven plugins one as the master branch is not building due to missing dependencies.

Where is the job building this repository?

### CODE REVIEW

**Comment by apupier** [comment]
please note that it is following the way it has been implemented before but i think that we may uncover more differences between the "repackaged" plugins and the original plugins in the future as it is done manually and the structure of the repackaged plugins are then different

**Comment by chirino** [comment]
Tried building this branch, got:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Red Hat Fuse :: redhat-fuse ........................ SUCCESS [  0.221 s]
[INFO] Red Hat Fuse :: fuse-tools ......................... SUCCESS [  0.007 s]
[INFO] Red Hat Fuse :: repackage-maven-plugin ............. SUCCESS [  2.755 s]
[INFO] Red Hat Fuse :: fuse-karaf ......................... SUCCESS [  0.006 s]
[INFO] Red Hat Fuse :: fuse-karaf-bom ..................... SUCCESS [  0.007 s]
[INFO] Red Hat Fuse :: fuse-eap ........................... SUCCESS [  0.007 s]
[INFO] Red Hat Fuse :: fuse-eap-bom ....................... SUCCESS [  0.006 s]
[INFO] Red Hat Fuse :: fuse-springboot .................... SUCCESS [  0.005 s]
[INFO] Red Hat Fuse :: fuse-springboot-bom ................ SUCCESS [  0.005 s]
[INFO] Red Hat Fuse :: fuse-maven-plugins ................. SUCCESS [  0.035 s]
[INFO] Red Hat Fuse :: spring-boot-maven-plugin ........... SUCCESS [  0.681 s]
[INFO] Red Hat Fuse :: fabric8-maven-plugin ............... SUCCESS [  0.605 s]
[INFO] Red Hat Fuse :: karaf-maven-plugin ................. FAILURE [  0.327 s]
[INFO] Red Hat Fuse :: karaf-services-maven-plugin ........ SKIPPED
[INFO] Red Hat Fuse :: camel-maven-plugin ................. SKIPPED
[INFO] Red Hat Fuse :: camel-salesforce-maven-plugin ...... SKIPPED
[INFO] Red Hat Fuse :: camel-package-maven-plugin ......... SKIPPED
[INFO] Red Hat Fuse :: camel-api-component-maven-plugin ... SKIPPED
[INFO] Red Hat Fuse :: camel-restdsl-swagger-plugin ....... SKIPPED
[INFO] Red Hat Fuse :: cxf-codegen-plugin ................. SKIPPED
[INFO] Red Hat Fuse :: cxf-java2swagger-plugin ............ SKIPPED
[INFO] Red Hat Fuse :: cxf-java2wadl-plugin ............... SKIPPED
[INFO] Red Hat Fuse :: cxf-java2ws-plugin ................. SKIPPED
[INFO] Red Hat Fuse :: cxf-wadl2java-plugin ............... SKIPPED
[INFO] Red Hat Fuse :: cxf-wsdl-validator-plugin .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.394 s
[INFO] Finished at: 2018-09-19T10:28:31-04:00
[INFO] Final Memory: 60M/521M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.redhat-fuse:repackage-maven-plugin:7.2.0-SNAPSHOT:repackage (repackage) on project karaf-maven-plugin: Execution repackage of goal org.jboss.redhat-fuse:repackage-maven-plugin:7.2.0-SNAPSHOT:repackage failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.redhat-fuse:repackage-maven-plugin:7.2.0-SNAPSHOT:repackage (repackage) on project karaf-maven-plugin: Execution repackage of goal org.jboss.redhat-fuse:repackage-maven-plugin:7.2.0-SNAPSHOT:repackage failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution repackage of goal org.jboss.redhat-fuse:repackage-maven-plugin:7.2.0-SNAPSHOT:repackage failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.jboss.fuse.mvnplugins.repackage.RepackageMojo.writeM2eConfiguration(RepackageMojo.java:123)
	at org.jboss.fuse.mvnplugins.repackage.RepackageMojo.execute(RepackageMojo.java:118)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karaf-maven-plugin


```

**Comment by apupier** [comment]
missed it as I developed it on master branch initially (which wasn't building completely) and there is no CI build for PR.

fixed (even if still no test)

**Comment by jamesnetherton** [comment]
Looks good to me. Maybe fix the dodgy indentation of `PLUGIN_DESCRIPTOR_PATH` on line 65.

**Comment by apupier** [comment]
> Looks good to me. Maybe fix the dodgy indentation of `PLUGIN_DESCRIPTOR_PATH` on line 65.

done, also removed tab indentation in other added lines.

**Pull request merged**
