### PR TITLE
ENTESB-13756 Remove scope from <dependencyManagement/> of redhat-fuse

### PR DESCRIPTION
**Pull request by cunningt**
https://issues.redhat.com/browse/ENTESB-13756

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by cunningt** [comment]
@grgrzybek Should we be removing the type as well for docker-maven-plugin?

**Comment by grgrzybek** [comment]
Please don't merge yet, I'll review in bulk with all the alignments.

**Comment by grgrzybek** [comment]
But definitely scope is not needed here

**Comment by cunningt** [comment]
Grzegorz's changes have gone through, talked to him on chat, he said it was okay to merge.

**Pull request merged**
